gustavo-alarcon/ingenieria-dsp

- src/app/main/pages/quality/analysis/progress/dialogs/analysis-dialog/analysis-dialog.component.ts
> 31 🐛 El sistema permite guardar acciones correctivas en blanco y repetidas

- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.component.html
- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.component.ts
- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.module.ts
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-approve/budgets-pending-approve.component.html
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-approve/budgets-pending-approve.component.scss
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-approve/budgets-pending-approve.component.ts
- src/app/main/pages/budgets/budgets/budgets-pending-send/dialogs/pending-send-update-dialog/pending-send-update-dialog.component.scss
- src/app/main/services/budgets.service.ts
> 26 HU#14 - Pestaña Pendientes de aprobación

- src/app/main/models/budgets.model.ts
- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.component.ts
- src/app/main/pages/budgets/budgets/budgets-summary/budgets-summary.component.html
- src/app/main/services/budgets.service.ts
Approve Dialog, ReJection Dialog
> ✨ Feature done

- src/app/main/models/budgets.model.ts
- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.component.html
- src/app/main/pages/budgets/budgets/budgets-pending-approval/budgets-pending-approval.component.ts
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-history/budgets-pending-history.component.html
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-history/budgets-pending-history.component.scss
- src/app/main/pages/budgets/budgets/budgets-pending-approval/dialogs/budgets-pending-history/budgets-pending-history.component.ts
- src/app/main/pages/budgets/budgets/budgets-summary/budgets-summary.component.html
- src/app/main/pages/budgets/budgets/budgets-summary/budgets-summary.component.ts
- src/app/main/pages/budgets/budgets/budgets-summary/dialogs/budgets-summary-timeline-dialog/budgets-summary-timeline-dialog.component.html
- src/app/main/pages/budgets/budgets/budgets-summary/dialogs/budgets-summary-timeline-dialog/budgets-summary-timeline-dialog.component.scss
- src/app/main/pages/budgets/budgets/budgets-summary/dialogs/budgets-summary-timeline-dialog/budgets-summary-timeline-dialog.component.ts
- src/app/main/services/budgets.service.ts
> 🔨 Fixes done

- src/app/main/pages/quality/analysis/progress/progress.component.ts
> 70 HU#03 - Prevenir el auto-close del diálogo de análisis en tablet

- src/app/main/pages/quality/analysis/progress/dialogs/analysis-dialog/analysis-dialog.component.html
- src/app/main/pages/quality/analysis/progress/dialogs/analysis-dialog/analysis-dialog.component.scss
- src/app/main/pages/quality/analysis/tracing/dialogs/acc-corrective-dialog/acc-corrective-dialog.component.html
> 67 HU#04 - Agrandar vista de controladores

- src/app/main/models/workshop.model.ts
- src/app/main/pages/quality/configurations/configurations.component.html
- src/app/main/pages/quality/configurations/configurations.component.ts
- src/app/main/services/quality.service.ts
Lista de procesos para talleres configuraciones
> 74 HU#08 - Listas de procesos por taller

- src/app/main/pages/quality/analysis/progress/progress.component.html
- src/app/main/pages/quality/analysis/records/records.component.html
- src/app/main/pages/quality/analysis/tracing/tracing.component.html
Actualizar diseño de tarjetas con nuevo formato de timer: DD / HH / MM
> 76 HU#10 - Actualizar formato de tarjetas de eventos

- src/app/main/pages/quality/analysis/results/results.component.html
- src/app/main/pages/quality/analysis/results/results.component.scss
- src/app/main/pages/quality/analysis/results/results.component.ts
> 72 HU#06 - Ordenar columnas de tabla Resultados

- src/app/main/main/main.component.scss
- src/app/main/models/quality.model.ts
- src/app/main/pages/quality/analysis/progress/progress.component.html
- src/app/main/pages/quality/analysis/progress/progress.component.ts
- src/app/main/pages/quality/analysis/records/records.component.html
- src/app/main/pages/quality/analysis/records/records.component.ts
- src/app/main/pages/quality/analysis/results/results.component.html
- src/app/main/pages/quality/analysis/results/results.component.ts
- src/app/main/pages/quality/analysis/tracing/tracing.component.html
- src/app/main/pages/quality/analysis/tracing/tracing.component.ts
- src/app/main/services/quality.service.ts
> 75 HU#09 - Agregar filtros de búsqueda en sección Análisis

- src/app/main/pages/quality/analysis/progress/dialogs/analysis-dialog/analysis-dialog.component.html
- src/app/main/pages/quality/analysis/progress/dialogs/analysis-dialog/analysis-dialog.component.ts
closes #101
:hammer: 🎨 Add additional fields to the analysis dialog
> 101 HU#01 - Agregar campos adicionales al dialogo analisis

- src/app/main/pages/quality/analysis/progress/progress.component.html
- src/app/main/pages/quality/analysis/results/results.component.html
- src/app/main/pages/quality/analysis/tracing/tracing.component.html
> :sparkles: Feature done

- src/app/main/models/quality.model.ts
- src/app/main/pages/quality/analysis/results/dialogs/detail-external-dialog/detail-external-dialog.component.html
- src/app/main/pages/quality/analysis/results/dialogs/detail-internal-dialog/detail-internal-dialog.component.html
- src/app/main/pages/quality/analysis/tracing/dialogs/detail-external-dialog/detail-external-dialog.component.html
- src/app/main/pages/quality/analysis/tracing/dialogs/detail-internal-dialog/detail-internal-dialog.component.html
> 102 HU#02 - Actualizar dialogo Detalles con campos adicionales (Actualización dialogo análisis)

- src/app/main/pages/quality/analysis/progress/dialogs/detail-external-dialog/detail-external-dialog.component.html
- src/app/main/pages/quality/analysis/progress/dialogs/detail-internal-dialog/detail-internal-dialog.component.html
- src/app/main/pages/quality/analysis/results/dialogs/detail-external-dialog/detail-external-dialog.component.html
- src/app/main/pages/quality/analysis/results/dialogs/detail-internal-dialog/detail-internal-dialog.component.html
- src/app/main/pages/quality/analysis/tracing/dialogs/detail-external-dialog/detail-external-dialog.component.html
- src/app/main/pages/quality/analysis/tracing/dialogs/detail-internal-dialog/detail-internal-dialog.component.html
closes #106
🔨 🎨 Change of name field causing failure
> 106 HU#04 - Cambio de nombre campo causante de falla

- src/app/main/pages/evaluations/evaluations-history/dialogs/history-observation-dialog/history-observation-dialog.component.html
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-observations-dialog/evaluations-observations-dialog.component.html
- src/app/main/pages/evaluations/evaluations-requests/dialogs/requests-observation-dialog/requests-observation-dialog.component.html
> 110 HU#08 - Actualizar usuario Creado por en dialogo observaciones

- src/app/main/models/evaluations.model.ts
- src/app/main/pages/evaluations/evaluations-history/evaluations-history.component.html
- src/app/main/pages/evaluations/evaluations-history/evaluations-history.component.ts
- src/app/main/pages/evaluations/evaluations-requests/dialogs/requests-create-dialog/requests-create-dialog.component.html
- src/app/main/pages/evaluations/evaluations-requests/dialogs/requests-create-dialog/requests-create-dialog.component.ts
closes #113
🔨 🎨 Update tallest column: Map codes by names
> 113 HU#11 - Actualizar columna Taller: Mapear códigos por nombres

- package-lock.json
- package.json
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-consults-dialog/evaluations-consults-dialog.component.html
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-consults-dialog/evaluations-consults-dialog.component.ts
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-finalize-dialog/evaluations-finalize-dialog.component.html
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-finalize-dialog/evaluations-finalize-dialog.component.ts
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-response-dialog/evaluations-response-dialog.component.html
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-response-dialog/evaluations-response-dialog.component.scss
- src/app/main/pages/evaluations/evaluations-progress/dialogs/evaluations-response-dialog/evaluations-response-dialog.component.ts
- src/styles.scss
> 130 :hammer: Implementar pluggin de dibujo en módulo pre-evaluaciones

- src/app/main/pages/budgets/budgets/budgets-pending-send/budgets-pending-send.component.html
- src/app/main/pages/budgets/budgets/budgets-pending-send/budgets-pending-send.component.ts
se agrego filtro y columnas taller en presupuestos pendientes de envio
> 132 Observación#01 - Agregar filtro de taller en sección presupuestos pestaña pdtes de envio

- .gitignore
- src/app/main/models/evaluations.model.ts
- src/app/main/pages/evaluations/evaluations-history/evaluations-history.component.ts
- src/app/main/services/evaluations.service.ts
closed #126
🎨 🔨 fix bug download file excel
> 126 Bug#02 - Mejorar el formato de descarga de la tabla de resultados - Módulo Pre-evaluaciones

- functions/index.js
- src/app/auth/pages/login/login.component.ts
se valido el login en la plataforma y al crear el usuario en la  funcion
> 157 valid domain @ferreyros.com.pe y @meraki-s.com 

- src/app/main/pages/spares/improvements/improvements.component.html
- src/app/main/pages/spares/improvements/improvements.component.ts
- src/assets/css/meraki.scss
> 160 📌 Filtros de estado - Mejoras

- src/app/main/models/improvenents.model.ts
- src/app/main/pages/spares/improvements/dialogs/create-dialog-improvenments/create-dialog-improvenments.component.html
- src/app/main/pages/spares/improvements/dialogs/create-dialog-improvenments/create-dialog-improvenments.component.scss
- src/app/main/pages/spares/improvements/dialogs/create-dialog-improvenments/create-dialog-improvenments.component.ts
- src/app/main/pages/spares/improvements/dialogs/edit-dialog-improvenments/edit-dialog-improvenments.component.html
- src/app/main/pages/spares/improvements/dialogs/edit-dialog-improvenments/edit-dialog-improvenments.component.scss
- src/app/main/pages/spares/improvements/dialogs/edit-dialog-improvenments/edit-dialog-improvenments.component.ts
- src/app/main/pages/spares/improvements/dialogs/replacement-dialog-improvements/replacement-dialog-improvements.component.html
- src/app/main/pages/spares/improvements/dialogs/replacement-dialog-improvements/replacement-dialog-improvements.component.scss
- src/app/main/pages/spares/improvements/dialogs/replacement-dialog-improvements/replacement-dialog-improvements.component.ts
- src/app/main/pages/spares/improvements/dialogs/show-dialog-improvements/show-dialog-improvements.component.html
- src/app/main/pages/spares/improvements/dialogs/show-dialog-improvements/show-dialog-improvements.component.sass
- src/app/main/pages/spares/improvements/dialogs/show-dialog-improvements/show-dialog-improvements.component.ts
- src/app/main/pages/spares/improvements/dialogs/validate-dialog-improvenments/validate-dialog-improvenments.component.html
- src/app/main/pages/spares/improvements/dialogs/validate-dialog-improvenments/validate-dialog-improvenments.component.scss
- src/app/main/pages/spares/improvements/dialogs/validate-dialog-improvenments/validate-dialog-improvenments.component.ts
- src/app/main/services/improvements.service.ts
> 162 📌 Controlador de comentarios - Mejoras

- src/app/auth/classes/ui-config.ts
- src/app/main/main-routing.module.ts
- src/app/main/main/main.component.html
- src/app/main/models/frequencySparePart.model.ts
- src/app/main/models/user-model.ts
- src/app/main/pages/spares/frequencies/frequencies-routing.module.ts
- src/app/main/pages/spares/frequencies/frequencies.component.html
- src/app/main/pages/spares/frequencies/frequencies.component.scss
- src/app/main/pages/spares/frequencies/frequencies.component.ts
- src/app/main/pages/spares/frequencies/frequencies.module.ts
- src/app/main/pages/spares/replacements/replacements.component.ts
- src/app/main/services/frequencies.service.ts
- src/assets/css/meraki.scss
Todos los criterios de aceptación, han sido implementados.
closes #164
> 164 📌 HU#01 Crear sección frecuencias

- src/app/main/pages/spares/frequencies/frequencies.component.html
- src/app/main/pages/spares/frequencies/frequencies.component.scss
> 166 📌 HU#03 Implementar filtro de búsqueda

- src/app/main/pages/spares/frequencies/dialogs/create-frequency-dialog/create-frequency-dialog.component.html
- src/app/main/pages/spares/frequencies/dialogs/create-frequency-dialog/create-frequency-dialog.component.scss
- src/app/main/pages/spares/frequencies/dialogs/create-frequency-dialog/create-frequency-dialog.component.ts
- src/app/main/pages/spares/frequencies/frequencies.component.ts
- src/app/main/pages/spares/frequencies/frequencies.module.ts
- src/app/main/pages/spares/replacements/dialogs/create-dialog-replacements/create-dialog-replacements.component.html
- src/app/main/pages/spares/replacements/dialogs/create-dialog-replacements/create-dialog-replacements.component.sass
- src/app/main/services/frequencies.service.ts
- src/assets/css/meraki.scss
> 167 📌 HU#04 Implementar creación

- src/app/main/main.module.ts
- src/app/main/pages/spares/frequencies/dialogs/edit-frequency-dialog/edit-frequency-dialog.component.html
- src/app/main/pages/spares/frequencies/dialogs/edit-frequency-dialog/edit-frequency-dialog.component.scss
- src/app/main/pages/spares/frequencies/dialogs/edit-frequency-dialog/edit-frequency-dialog.component.ts
- src/app/main/pages/spares/frequencies/frequencies.component.ts
- src/app/main/pages/spares/frequencies/frequencies.module.ts
- src/app/main/services/frequencies.service.ts
> 168 📌 HU#05 Implementar edición

- src/app/main/pages/spares/frequencies/dialogs/create-frequency-dialog/create-frequency-dialog.component.html
- src/app/main/pages/spares/frequencies/dialogs/delete-frequency-dialog/delete-frequency-dialog.component.html
- src/app/main/pages/spares/frequencies/dialogs/delete-frequency-dialog/delete-frequency-dialog.component.scss
- src/app/main/pages/spares/frequencies/dialogs/delete-frequency-dialog/delete-frequency-dialog.component.ts
- src/app/main/pages/spares/frequencies/dialogs/edit-frequency-dialog/edit-frequency-dialog.component.html
- src/app/main/pages/spares/frequencies/frequencies.component.ts
- src/app/main/pages/spares/frequencies/frequencies.module.ts
- src/app/main/services/frequencies.service.ts
> 169 📌 HU#06 Implementar borrar

- src/app/auth/models/generalConfig.model.ts
- src/app/main/models/generalConfig.model.ts
- src/app/main/models/improvenents.model.ts
- src/app/main/pages/spares/spare-parts/spare-parts.component.html
- src/app/main/pages/spares/spare-parts/spare-parts.component.scss
- src/app/main/pages/spares/spare-parts/spare-parts.component.ts
- src/app/main/services/frequencies.service.ts
- src/app/main/services/improvements.service.ts
> 170 📌 HU#07 Implementar análisis de frecuencia

- src/app/main/models/frequencySparePart.model.ts
- src/app/main/pages/spares/spare-parts/dialogs/ot-dialog/ot-dialog.component.html
- src/app/main/pages/spares/spare-parts/dialogs/ot-dialog/ot-dialog.component.scss
- src/app/main/pages/spares/spare-parts/dialogs/ot-dialog/ot-dialog.component.ts
- src/app/main/pages/spares/spare-parts/spare-parts.component.ts
- src/app/main/pages/spares/spare-parts/spare-parts.module.ts
- src/app/main/services/frequencies.service.ts
> 171 📌 HU#08 Implementar monitor de actividad
